#!/bin/bash

USAGE="Usage: $0 <streamname>"

if [ $# -lt 1 ] ; then
	echo $USAGE >&2
	exit -1
fi

TOPIC=$1
SCRIPTDIR=$(cd $(dirname $0) && pwd -P)
PYTHONDIR=$SCRIPTDIR/python

cd $PYTHONDIR
./kinesisProducer.py -n $TOPIC
