CONNECT / AS SYSDBA;     

ALTER SYSTEM SET      
   log_archive_dest_1 = 'location=/u01/app/oracle/archives'      
   SCOPE=SPFILE;

SHUTDOWN IMMEDIATE; 
STARTUP MOUNT; 
ALTER DATABASE ARCHIVELOG; 
ALTER DATABASE OPEN; 
SHUTDOWN IMMEDIATE; 
STARTUP;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
COMMIT;

CREATE USER "ORACAPTL" PROFILE "DEFAULT"
    IDENTIFIED BY "ORACAPTL" 
    ACCOUNT UNLOCK;
GRANT "CONNECT"      TO "ORACAPTL";
GRANT CREATE SESSION TO "ORACAPTL";
--
-- GRANTS for GUI (Navigator) use to get database name
--
GRANT SELECT ON "PUBLIC"."V$PARAMETER"     TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$SPPARAMETER"   TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$INSTANCE"      TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$DATABASE"      TO "ORACAPTL";
--
-- To add supplemental logging to tables, we require ALTER
--
GRANT SELECT ANY TABLE                     TO "ORACAPTL";
GRANT ALTER ANY TABLE                      TO "ORACAPTL";
--
-- GRANTS for capture process user
--
-- Accessed periodically during extraction to retrieve log file 
-- and node information
--
GRANT SELECT ON "PUBLIC"."V$ARCHIVED_LOG"           TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$DATABASE"               TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$LOG"                    TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$LOGFILE"                TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$TRANSPORTABLE_PLATFORM" TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$THREAD"                 TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$DATABASE_INCARNATION"   TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$SPPARAMETER"            TO "ORACAPTL";
GRANT SELECT ON "PUBLIC"."V$STANDBY_LOG"            TO "ORACAPTL";
--
-- GRANTS for collecting metadata during extraction initialization
--
GRANT SELECT ON "SYS"."ALL_TABLES"              TO "ORACAPTL";
GRANT SELECT ON "SYS"."ALL_TAB_PARTITIONS"      TO "ORACAPTL";
GRANT SELECT ON "SYS"."DBA_LOG_GROUPS"          TO "ORACAPTL";
GRANT SELECT ON "SYS"."DBA_LOG_GROUP_COLUMNS"   TO "ORACAPTL";
GRANT SELECT ON "SYS"."DBA_USERS"                    TO "ORACAPTL";
GRANT SELECT ON "SYS"."DBA_TABLESPACES"         TO "ORACAPTL";
GRANT SELECT ON "SYS"."USER$"                   TO "ORACAPTL";
GRANT SELECT ON "SYS"."OBJ$"                    TO "ORACAPTL";
GRANT SELECT ON "SYS"."TAB$"                    TO "ORACAPTL";
GRANT SELECT ON "SYS"."IND$"                    TO "ORACAPTL";
GRANT SELECT ON "SYS"."COL$"                    TO "ORACAPTL";
GRANT SELECT ON "SYS"."PARTOBJ$"                TO "ORACAPTL";
GRANT SELECT ON "SYS"."TABPART$"                TO "ORACAPTL";
GRANT SELECT ON "SYS"."INDPART$"                TO "ORACAPTL";
GRANT SELECT ON "SYS"."TABCOMPART$"             TO "ORACAPTL";
GRANT SELECT ON "SYS"."TABSUBPART$"             TO "ORACAPTL";

--
-- For testing, create an IVP table
--
CREATE TABLE ORACAPTL.IVP000 
(KEY_ID INTEGER NOT NULL ENABLE, 
 DTA1 VARCHAR2(100), 
 DTA2 NUMBER(5), 
 PRIMARY KEY (KEY_ID), 
 SUPPLEMENTAL LOG DATA (ALL) COLUMNS);

ALTER USER ORACAPTL 
 DEFAULT TABLESPACE "USERS" 
 TEMPORARY TABLESPACE "TEMP"
QUOTA 10M ON "USERS"; 

INSERT INTO ORACAPTL.IVP000 VALUES (1,1,1);

COMMIT;
